draw_set_font(font_Levels)
draw_set_halign(fa_center)
draw_set_valign(fa_center)
draw_text(room_width/2, room_height/2+100,  "Placar: " + string(score))
draw_text(room_width/2, room_height/2,  "Tente novamente comandante")
draw_text(room_width/2, room_height/2-50,  "Você não pode deixar as forças do mal conquistarem a galáxia!")